const assert = require('node:assert/strict');
const {performance} = require('node:perf_hooks');
const A = require('../agrupacion-reportes.js');
const r = (id, metros=0, estado='Pendiente') => ({id,lat:-1.0788+metros/111195,lon:-79.4984,estado});
assert.equal(A.agrupar([r('a'),r('b',25)]).criticos.length,0);
const cercanos=[r('a'),r('b',25),r('c',65)];
assert.equal(A.agrupar(cercanos).criticos.length,1);
assert.equal(A.agrupar(cercanos).porReporte.size,3);
assert.equal(A.agrupar([r('a'),r('b',50),r('c',101)]).criticos.length,0,'No encadenar puntos separados más de 100 m');
assert.equal(A.agrupar([r('a'),r('b',25),r('c',65,'Atendido')]).criticos.length,0);
assert.equal(A.agrupar([r('a'),r('b',25),r('c',65,'Descartado')]).criticos.length,0);
assert.equal(A.agrupar([r('a'),r('b',25),r('c',65,'En revisión')]).criticos.length,1);
const dos=[...cercanos,r('d',500),r('e',530),r('f',560)];
const agrupados=A.agrupar(dos);
assert.equal(agrupados.criticos.length,2);
assert.deepEqual(A.agrupar([...dos].reverse()).criticos.map(g=>g.miembros.map(r=>r.id)),agrupados.criticos.map(g=>g.miembros.map(r=>r.id)));
assert.equal(A.agrupar([r('a'),r('b'),r('c')]).criticos.length,1,'GPS idénticos');
assert.equal(A.ubicacionValida({...r('a'),lat:null}),false);
assert.equal(A.ubicacionValida({...r('a'),lat:NaN}),false);
assert.equal(A.ubicacionValida({...r('a'),lon:181}),false);
assert.equal(A.ubicacionValida({...r('a'),lon:''}),false);
for(const g of agrupados.criticos)assert(g.miembros.includes(g.destino),'Ruta a un reporte real');
const start=performance.now();const mil=Array.from({length:1000},(_,i)=>r(String(i).padStart(4,'0'),(i%5)*10));
const grandes=A.agrupar(mil);
assert.equal(grandes.porReporte.size,1000);
assert.equal(new Set(grandes.criticos.flatMap(g=>g.miembros.map(r=>r.id))).size,1000);
console.log('PASS: distancia, umbral, estados, cadenas, orden estable, GPS idéntico, datos inválidos, destino y 1000 reportes. Tiempo: '+Math.round(performance.now()-start)+' ms');
